spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri: http://localhost:8081/
          predicates:
            - Path= /products/**
        - id : r2
          uri: http://localhost:8761/
          predicates:
            - Path= /customers/**
    discovery:
      enabled: false
  server:
    port: 8888